trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
# This task trigger a new build to run, this build is the same as the step above that generates the bundle
- task: Npm@1 # Run npm install
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: '$(System.DefaultWorkingDirectory)'
- task: Npm@1 # Run npm run build
  displayName: 'npm run build'
  inputs:
    command: custom
    customCommand: run build

- publish: 'www/' # Publish App artifact
  artifact: 'www'
  displayName: 'Publishing Artifact'

- bash: | # Installing cordova
    sudo npm i -g cordova
  displayName: 'npm i -g cordova@latest'

- bash: | # Install ionic cli
    sudo npm install -g @ionic/cli
  displayName: 'npm i -g @ionic/cli'

# Needed to solve missing dependency problem, see the troubleshooting topic
- bash: |
    sudo apt-get install lib32z1
  displayName: 'sudo apt-get install lib32z1'
- task: gulp@1
  inputs:
    targets: prod-ios
    gulpjs: '$(System.DefaultWorkingDirectory)/gulpfile.js'
  displayName: 'Run gulp task'
    
- bash: | # Running gulp to create the apk
    gulp prod-ios
  displayName: 'Execute gulp prod-android'
