trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
# This task trigger a new build to run, this build is the same as the step above that generates the bundle
- task: Npm@1 # Run npm install
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: '$(System.DefaultWorkingDirectory)'
- task: Npm@1 # Run npm run build
  displayName: 'npm run build'
  inputs:
    command: custom
    customCommand: run build

- publish: 'www/' # Publish App artifact
  artifact: 'www'
  displayName: 'Publishing Artifact'

- bash: | # Installing cordova
    sudo npm i -g cordova
  displayName: 'npm i -g cordova@latest'

- bash: | # Install ionic cli
    sudo npm install -g @ionic/cli
  displayName: 'npm i -g @ionic/cli'

- bash: | # Install Gulp CLI
    sudo npm install --global gulp-cli
  displayName: 'npm install --global gulp-cli'

- task: gulp@1
  inputs:
    targets: prod-ios
    gulpjs: '$(System.DefaultWorkingDirectory)/gulpfile.js'
  displayName: 'Run gulp task'
    
- bash: | # Running gulp to create the apk
    gulp prod-ios
  displayName: 'Execute gulp prod-android'

- bash: | # List all the files in the project Directory
    ls -la
  displayName: 'ls -la'

- task: Xcode@5
  inputs:
    actions: 'build'
    sdk: 'iphoneos'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    packageApp: true
    useXcpretty: false
    scheme: 'CordovaLib'

- task: ArchiveFiles@2
  displayName: 'Package .xcarchive into a zip file'
  inputs:
    rootFolderOrFile: '$(agent.buildDirectory)/CordovaLib.xcarchive/'
    archiveFile: '$(build.artifactStagingDirectory)/CordovaLib.xcarchive.zip'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/CordovaLib.xcarchive.zip'
    artifactName: 'xcarchive-files'
    artifactType: 'container'
